name: ost_tracker_og
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_spinkit: ^5.2.0
  cloud_firestore: ^4.9.2
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
